INSERT INTO USER(email, name, password) VALUES('pedro.hvieira@live.com', 'Pedro Vieira', '$2a$10$FR1XxDxvmR1JcIQ6M6I1gO8PPVkTZ5.ilzjyTpHam2KSsL/Dj.Rim');

INSERT INTO PRODUCER(name) values('Producer 1');
INSERT INTO PRODUCER(name) values('Producer 2');
INSERT INTO PRODUCER(name) values('Producer 3');
INSERT INTO PRODUCER(name) values('Producer 4');
INSERT INTO PRODUCER(name) values('Producer 5');
INSERT INTO PRODUCER(name) values('Producer 6');

INSERT INTO STUDIO(name) values('Studio 1');
INSERT INTO STUDIO(name) values('Studio 2');
INSERT INTO STUDIO(name) values('Studio 3');

INSERT INTO TITLE(NAME, STUDIO_ID) VALUES ('Title 1', 1);
INSERT INTO TITLE(NAME, STUDIO_ID) VALUES ('Title 2', 1);
INSERT INTO TITLE(NAME, STUDIO_ID) VALUES ('Title 3', 1);
INSERT INTO TITLE(NAME, STUDIO_ID) VALUES ('Title 4', 2);
INSERT INTO TITLE(NAME, STUDIO_ID) VALUES ('Title 5', 2);
INSERT INTO TITLE(NAME, STUDIO_ID) VALUES ('Title 6', 3);
INSERT INTO TITLE(NAME, STUDIO_ID) VALUES ('Title 7', 3);

INSERT INTO TITLE_PRODUCERS(TITLE_ID, PRODUCERS_ID) VALUES (1, 5);
INSERT INTO TITLE_PRODUCERS(TITLE_ID, PRODUCERS_ID) VALUES (2, 5);
INSERT INTO TITLE_PRODUCERS(TITLE_ID, PRODUCERS_ID) VALUES (3, 6);
INSERT INTO TITLE_PRODUCERS(TITLE_ID, PRODUCERS_ID) VALUES (4, 4);
INSERT INTO TITLE_PRODUCERS(TITLE_ID, PRODUCERS_ID) VALUES (5, 3);
INSERT INTO TITLE_PRODUCERS(TITLE_ID, PRODUCERS_ID) VALUES (6, 2);
INSERT INTO TITLE_PRODUCERS(TITLE_ID, PRODUCERS_ID) VALUES (7, 1);

INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1990, 1, 1);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1990, 2, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1990, 3, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1990, 4, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1990, 5, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1990, 6, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1990, 7, 0);

INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1999, 1, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1999, 2, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1999, 3, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1999, 4, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1999, 5, 1);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1999, 6, 0);
INSERT INTO INDICATION(YEAR, TITLE_ID, WINNER) VALUES(1999, 7, 0);